import numpy as np
import pickle
import os
import json

# load what we need from the config file
with open(os.path.abspath(os.path.dirname(__file__)) +'/../../config.json','r') as f:
    config = json.load(f)

BASE_PATH = config['RecordingFolder'] # folder with all of the files generated by Suite2P for this recording (F.npy, iscell.npy, etc)
traces_file = config['AnalysisFile']

def main():
    stat = np.load(BASE_PATH+"stat.npy",allow_pickle=True)
    
    # load our dictionary
    with open(BASE_PATH + traces_file, 'rb') as f:
        cell_dict = pickle.load(f)

    # add the x and y coordinates to the cell dictionary
    for cell in cell_dict:
        this_cell_x = stat[cell-1]["med"][0]
        this_cell_y = stat[cell-1]["med"][1]

        cell_dict[cell]['x'] = this_cell_x
        cell_dict[cell]['y'] = this_cell_y
    
    # save it
    with open(BASE_PATH + traces_file, 'wb') as f:
        pickle.dump(cell_dict,f)

if __name__=="__main__":
    main()