"""
Add the x and y coordinates for each cell relative to the field of view of the recording to the big dictionary
INPUT: stat.npy (Suite2P output), cell_dictionary.pkl
OUTPUT: cell_dictionary.pkl with new keys 'x' and 'y' containing the coordinates TODO (update)
AUTHOR: Veronica Tarka, May 2022, veronica.tarka@mail.mcgill.ca
"""

import numpy as np
import pickle
import os
import json

# load what we need from the config file
with open(os.path.abspath(os.path.dirname(__file__)) +'/../../config.json','r') as f:
    config = json.load(f)

BASE_PATH = config['RecordingFolder'] # folder with all of the files generated by Suite2P for this recording (F.npy, iscell.npy, etc)
CELL_DICT_FILE = config['AnalysisFile']

def main():
    # load the Suite2P output file that contains the x and y coordinates for the cells
    stat = np.load(BASE_PATH+"stat.npy",allow_pickle=True)
    
    # load our dictionary
    with open(BASE_PATH + CELL_DICT_FILE, 'rb') as f:
        cell_dict = pickle.load(f)

    # add the x and y coordinates to the cell dictionary
    for cell in cell_dict:
        this_cell_x = stat[cell-1]["med"][0]
        this_cell_y = stat[cell-1]["med"][1]

        cell_dict[cell]['x'] = this_cell_x
        cell_dict[cell]['y'] = this_cell_y

        cell_dict[cell]['xs'] = stat[cell-1]["xpix"]
        cell_dict[cell]['ys'] = stat[cell-1]["ypix"]
    
    # save it
    with open(BASE_PATH + CELL_DICT_FILE, 'wb') as f:
        pickle.dump(cell_dict,f)

if __name__=="__main__":
    main()