"""
Script to take the 2P output from recordings that were processed together, and split them into separate files.
INPUT: TODO
OUTPUT: TODO
AUTHOR: Veronica Tarka, August 2022, veronica.tarka@mail.mcgill.ca
"""

import numpy as np

BASE_PATH = "/media/vtarka/USB DISK/Lab/2P/222_226_combined/"
JUNCTURE_FRAME  = 8519
def main():
    # load our files that were generated by Suite2P and the stim files
    fluorescence_trace = np.load(BASE_PATH + "F.npy",allow_pickle=True) # uncorrected trace of dF/F
    neuropil_trace = np.load(BASE_PATH + "Fneu.npy",allow_pickle=True) # estimation of background fluorescence

    Fluo222 = fluorescence_trace[:,:JUNCTURE_FRAME]
    Fluo226 = fluorescence_trace[:,JUNCTURE_FRAME:]

    Fneu222 = neuropil_trace[:,:JUNCTURE_FRAME]
    Fneu226 = neuropil_trace[:,JUNCTURE_FRAME:]

    np.save(BASE_PATH + "Vid_222s/F.npy",Fluo222)
    np.save(BASE_PATH + "Vid_222s/Fneu.npy",Fneu222)

    np.save(BASE_PATH + "Vid_226s/F.npy",Fluo226)
    np.save(BASE_PATH + "Vid_226s/Fneu.npy",Fneu226)

if __name__=="__main__":
    main()