"""
Script to take the 2P output from recordings that were processed together, and split them into separate files.
INPUT: TODO
OUTPUT: TODO
AUTHOR: Veronica Tarka, August 2022, veronica.tarka@mail.mcgill.ca
"""
# TODO : Somehow the triggers seem to be shifted forward by 1 frame (see cell 133 as an example)
import numpy as np
import json
import os

# load what we need from the config file
with open(os.path.abspath(os.path.dirname(__file__)) +'/../../config.json','r') as f:
    config = json.load(f)

BASE_PATH = config['RecordingFolder'] # folder with all of the files generated by Suite2P for this recording (F.npy, iscell.npy, etc)
CSV_PATH = config['Triggers'] # name of CSV (assumed to be in the folder given in line above) with the trigger voltages over the recording

def main():
    # load our files that were generated by Suite2P and the stim files
    fluorescence_trace = np.load(BASE_PATH + "F.npy",allow_pickle=True) # uncorrected trace of dF/F
    neuropil_trace = np.load(BASE_PATH + "Fneu.npy",allow_pickle=True) # estimation of background fluorescence
    # stimulus = np.genfromtxt(BASE_PATH + CSV_PATH,delimiter=',',skip_header=True) # voltage values of the trigger software over the recording
    
    juncture_frame = 7630
    #round(len(stimulus)/100*10)

    Fluo222 = fluorescence_trace[:,:juncture_frame]
    Fluo226 = fluorescence_trace[:,juncture_frame:]

    Fneu222 = neuropil_trace[:,:juncture_frame]
    Fneu226 = neuropil_trace[:,juncture_frame:]

    np.save(BASE_PATH + "Vid_238s/F.npy",Fluo222)
    np.save(BASE_PATH + "Vid_238s/Fneu.npy",Fneu222)

    np.save(BASE_PATH + "Vid_239s/F.npy",Fluo226)
    np.save(BASE_PATH + "Vid_239s/Fneu.npy",Fneu226)

if __name__=="__main__":
    main()