"""
TODO format all
"""

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import random
import json
import os
import pickle


# load what we need from the config file
with open(os.path.abspath(os.path.dirname(__file__)) +'/../../../config.json','r') as f:
    config = json.load(f)

BASE_PATH = config['RecordingFolder'] # folder with all of the files generated by Suite2P for this recording (F.npy, iscell.npy, etc)
# csv_path = config['Triggers'] # name of CSV (assumed to be in the folder given in line above) with the trigger voltages over the recording
# conditions_path = config['Conditions'] # name of the CSV (assumed to be in folder given two lines above) with the condition types of each trial (freq, intensity, etc)
# output_path = config['AnalysisFile'] # name of the file that all of the analysis is getting saved in (tuning, best frequency, etc)
# STIMULUS_FRAMERATE = config['TriggerFR']
# TRIGGER_DELAY_IN_MS = config['TriggerDelay'] # delay between TDT sending a trigger and the stimulus actually happening
RECORDING_FRAMERATE = config['RecordingFR']
EPOCH_START_IN_MS = config['EpochStart']
# EPOCH_END_IN_MS = config['EpochEnd']
cell_dictionary_file = config['AnalysisFile']

def plot_events(cell_trace,events):
    for i in range(len(events[0])):
        plt.axvline(x=events[0][i])
    
    plt.plot(cell_trace,linewidth=2,color='black')
    plt.show()

def main():

    with open(BASE_PATH+"corrcoefs.pkl",'rb') as f:
        coeffs = pickle.load(f)

    coeffs[coeffs>0.99] = 0

    plt.imshow(coeffs)
    plt.show()

if __name__=="__main__":
    main()